name: flan-t5-xl3
channels:
  - pytorch
  - conda-forge
  - defaults
  - fastchan
  - apple
dependencies:
  - python=3.10
  - pip>=22.2

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```

  - numpy=1.23
  - openh264=2.3
  - py-opencv=4.6
  - scipy=1.9
  - tensorboard=2.11.0
  - transformers=4.23
  - matplotlib=3.6.2
  - scikit-image
  - scikit-learn
  - apple::tensorflow-deps
  - pip:
      - tqdm
      - better_exceptions
      - bpython
      - imutils
      - uritools
      - rich[jupyter]
      - icecream
      - black[jupyter]
      - pylint
      - isort
      - autopep8
      - autoflake
      - pdbpp
      - mlxtend
      - logging_tree
      - loguru
      - pydantic[email]
      - picklescan
      - pytype
      - pyannotate
      - mypy
      - py-spy
      - watermark
      - memray
      - tensorflow-macos
      - tensorflow-metal
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
